import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-inter",
});

export const metadata = {
  title: "Salamander Tracker",
  description: "Generated by create next app",
  icons: {
    icon: '/salamander.png', 
  },
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <link rel="icon" href="/salamander.png" type="image/png" />
      </head>
      <body className={inter.variable}>
        {children}
      </body>
    </html>
  );
} 