FROM node:20-slim

RUN apt-get update && \
    apt-get install -y openjdk-17-jdk ffmpeg && \
    apt-get clean

WORKDIR /app/server

COPY backend/server/package*.json ./

RUN npm install --only=production

COPY backend/server/. .

COPY backend/server/videos ./videos

COPY Processor/target/centroidFinderVideo-jar-with-dependencies.jar /app/server/

EXPOSE 3000

CMD ["node", "server.js"]